# Check PyTorch in your anaconda

In [1]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.9962, 0.2155, 0.3744],
        [0.1110, 0.6797, 0.8736],
        [0.0893, 0.1753, 0.7740],
        [0.6276, 0.9398, 0.2960],
        [0.7354, 0.0955, 0.4253]])


In [2]:
import torch
torch.cuda.is_available()

True

# Tensor data structure Introduction:
Tensors is an n-dimensional array data structure, which supports us to calculate matrix similar to numpy array, but it can run on both CPU and GPU. Tensors are optimized for AutoGrad derivative calculations.

In [3]:
import torch
import numpy as np

# 1. Create Tensor
### 1.1 directly from data

In [4]:
# The data type is automatically inferred.
data = [[1, 2],[3, 4]]
tensor_data = torch.tensor(data)
tensor_data

tensor([[1, 2],
        [3, 4]])

### 1.2 Create Tensor directly from Numpy Array

In [5]:
np_array = np.array(data)
tensor_from_np = torch.from_numpy(np_array)
tensor_from_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

### 1.3   from another tensor

In [6]:
x_ones = torch.ones_like(tensor_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(tensor_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3438, 0.3937],
        [0.6611, 0.7130]]) 



### 1.4 from a constant

shape is a kind of tuple which repesent n-dimesions of a tensor

In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4181, 0.6533, 0.3484],
        [0.8111, 0.6887, 0.8871]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 2. Properties of Tensor
including shape, datatype, and device

In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Tensor maths
There are many maths on tensors (>100) including arithmetic, algebra, matrix, random... Reference link: https://pytorch.org/docs/stable/torch.html.

Tensor maths are capable of running on the GPU (which will usually be faster than the CPU).

Tensors are initialized by default on the CPU. Using .to(device) convert tensors to GPU.

Note: transferring large amounts of tensors between devices can be time consuming and memory intensive

In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    
tensor

tensor([[0.8675, 0.5299, 0.0769, 0.0608],
        [0.7778, 0.2030, 0.9361, 0.7472],
        [0.3654, 0.4420, 0.7452, 0.8739]], device='cuda:0')

### 2.1 Indexing and slicing (similar to numpy):

In [12]:
tensor = torch.randint(10, (4, 4))
display(tensor)

print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[:, -1])
tensor[:,1] = 0
print(tensor)

tensor([[8, 0, 9, 5],
        [4, 8, 0, 4],
        [3, 0, 2, 0],
        [6, 8, 0, 5]])

First row:  tensor([8, 0, 9, 5])
First column:  tensor([8, 4, 3, 6])
Last column: tensor([5, 4, 0, 5])
tensor([[8, 0, 9, 5],
        [4, 0, 0, 4],
        [3, 0, 2, 0],
        [6, 0, 0, 5]])


### 2.2. Joining tensors

In [13]:
# we use cat() of torch package
t1 = torch.cat([tensor, tensor, tensor], dim=1)
display(tensor.shape)
display(t1.shape)
print(t1)

torch.Size([4, 4])

torch.Size([4, 12])

tensor([[8, 0, 9, 5, 8, 0, 9, 5, 8, 0, 9, 5],
        [4, 0, 0, 4, 4, 0, 0, 4, 4, 0, 0, 4],
        [3, 0, 2, 0, 3, 0, 2, 0, 3, 0, 2, 0],
        [6, 0, 0, 5, 6, 0, 0, 5, 6, 0, 0, 5]])


### 2.3 Tensor arithmetic 

In [21]:
# Matrix multiplication. y1, y2, y3 give the same result
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.ones_like(tensor)

torch.matmul(tensor, tensor.T, out=y3)
display(y1, y2, y3)

# Element-wise multiplication
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.ones_like(tensor)
torch.mul(tensor, tensor, out=z3)

display(z1, z2, z3)

tensor([[170,  52,  42,  73],
        [ 52,  32,  12,  44],
        [ 42,  12,  13,  18],
        [ 73,  44,  18,  61]])

tensor([[170,  52,  42,  73],
        [ 52,  32,  12,  44],
        [ 42,  12,  13,  18],
        [ 73,  44,  18,  61]])

tensor([[170,  52,  42,  73],
        [ 52,  32,  12,  44],
        [ 42,  12,  13,  18],
        [ 73,  44,  18,  61]])

tensor([[64,  0, 81, 25],
        [16,  0,  0, 16],
        [ 9,  0,  4,  0],
        [36,  0,  0, 25]])

tensor([[64,  0, 81, 25],
        [16,  0,  0, 16],
        [ 9,  0,  4,  0],
        [36,  0,  0, 25]])

tensor([[64,  0, 81, 25],
        [16,  0,  0, 16],
        [ 9,  0,  4,  0],
        [36,  0,  0, 25]])

### Single-element tensors 

In [22]:
# One-element tensor can be converted to a number in Python using the item() function.
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))


46 <class 'int'>


### In-place 
Save the result in the function call variable. Indicated by the suffix _.

For example, x.copy_(y), x.t_() will change the variable x.

In [26]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[13,  5, 14, 10],
        [ 9,  5,  5,  9],
        [ 8,  5,  7,  5],
        [11,  5,  5, 10]]) 

tensor([[18, 10, 19, 15],
        [14, 10, 10, 14],
        [13, 10, 12, 10],
        [16, 10, 10, 15]])


# 3. Relate to NumPy
Tensors on CPUs and NumPy arrays can share the same memory address, so changing one will change the other.

### 3.1 From Tensor to NumPy array

In [36]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [39]:
# Changes of the Tensor can change the NumPy array.
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]


### 3.2 From NumPy to Tensor array

In [37]:
n = np.ones(5)
t = torch.from_numpy(n)

In [40]:
# Changes of the NumPy array can change the Tensor.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
n: [4. 4. 4. 4. 4.]
